/**
 * Emits a sibling `*.slab.d.ts` for TypeScript consumers — see docs/LANGUAGE.md (Compilation outputs).
 */

import type { CompilerOutput, UniformBindingMeta } from "./types.js";

/**
 * Checks if a uniform should be included in the emitted d.ts.
 * Only mutable uniforms appear in the generated options type.
 */
function isEmittableUniform(u: UniformBindingMeta): boolean {
  return u.mousePosition || u.mutable === true || u.deferred === true;
}

function fileBasename(p: string, ext?: string): string {
  const s = p.replace(/\\/g, "/");
  const i = s.lastIndexOf("/");
  const name = i === -1 ? s : s.slice(i + 1);
  return ext != null && name.endsWith(ext) ? name.slice(0, -ext.length) : name;
}

function toPascalCase(id: string): string {
  const parts = id.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "Shader";
  return parts.map((p) => p[0]!.toUpperCase() + p.slice(1)).join("");
}

function uniformsInterfaceName(shaderId: string): string {
  return `${toPascalCase(shaderId)}Options`;
}

function jsdocLines(lines: string[], base: string): string {
  if (lines.length === 0) return "";
  if (lines.length === 1) return `${base}/** ${lines[0]} */\n`;
  return `${base}/**\n${lines.map((l) => `${base} * ${l}`).join("\n")}\n${base} */\n`;
}

function emitUniformField(u: UniformBindingMeta): string {
  const ind = "    ";
  const docs: string[] = [];

  if (u.mousePosition) {
    docs.push("mouse position in normalized canvas coordinates (read-only)");
    return `${jsdocLines(docs, ind)}${ind}readonly ${u.name}: readonly [number, number];\n`;
  }

  if ((u.slabType === "float" || u.slabType === "int") && u.range) {
    docs.push(`range: ${u.range[0]}-${u.range[1]}`);
  }
  if (u.hint === "color" && (u.slabType === "vec3" || u.slabType === "vec4")) {
    docs.push("color hint (same tuple shape as vec3/vec4)");
  }

  let ts: string;
  switch (u.slabType) {
    case "float":
    case "int":
      ts = "number";
      break;
    case "bool":
      ts = "boolean";
      break;
    case "vec2":
      ts = "[number, number]";
      break;
    case "vec3":
      ts = "[number, number, number]";
      break;
    case "vec4":
      ts = "[number, number, number, number]";
      break;
    case "sampler2D":
      ts = "HTMLImageElement | HTMLCanvasElement | ImageBitmap";
      break;
    default:
      ts = "unknown";
  }

  if (u.deferred) {
    ts = `${ts} | Deferred<${ts}>`;
  }

  // If there's a default, or it's not deferred, we might want to make it optional.
  // For safety and strictness, if it's deferred and has no default, it's required.
  // Actually, let's just make everything optional unless it is deferred without a default.
  const isRequired = u.deferred && u.default === null;
  const opt = isRequired ? "" : "?";

  return `${jsdocLines(docs, ind)}${ind}${u.name}${opt}: ${ts};\n`;
}

function emitUniformsInterface(shaderId: string, uniforms: readonly UniformBindingMeta[]): string {
  const name = uniformsInterfaceName(shaderId);
  const emittable = uniforms.filter(isEmittableUniform);
  const fields = emittable.map((u) => emitUniformField(u)).join("");
  return `  export interface ${name} {\n${fields}    augments?: AugmentRef[];\n  }\n`;
}

function emitInnerBody(output: CompilerOutput, _slabStem: string): string {
  const lines: string[] = [];
  lines.push(`  export type Deferred<T> = { readonly __deferred: true; readonly __type: T };\n\n`);
  for (const sh of output.shaders) {
    lines.push(emitUniformsInterface(sh.id, sh.metadata.uniforms));
  }
  lines.push(
    `  export function __invokeSlabFrame(frameId: string, options?: SlabFrameCallOptions): ShaderFrameInstance;\n`,
  );
  lines.push(`  export const __slabFrameIds: readonly string[];\n`);
  return lines.join("");
}

/**
 * @param slabSourcePath Absolute or relative path to the `.slab` file (basename drives `declare module "./<file>.slab"`).
 */
export function emitSlabDts(output: CompilerOutput, slabSourcePath: string): string {
  const slabBase = fileBasename(slabSourcePath);
  const slabStem = fileBasename(slabSourcePath, ".slab");
  const inner = emitInnerBody(output, slabStem);
  return [
    "// Auto-generated by shaderlab — do not edit\n",
    `// Source: ${slabBase}\n\n`,
    `declare module "./${slabBase}" {\n`,
    '  import type { ShaderFrameInstance, SlabFrameCallOptions } from "@yoruxiii/shaderlab";\n\n',
    inner,
    "}\n\nexport {};\n",
  ].join("");
}
