/**
 * Emits a sibling `*.slab.d.ts` for TypeScript consumers — see docs/LANGUAGE.md (Compilation outputs).
 */

import type { CompilerOutput, UniformBindingMeta } from "./types.js";

function fileBasename(p: string, ext?: string): string {
  const s = p.replace(/\\/g, "/");
  const i = s.lastIndexOf("/");
  const name = i === -1 ? s : s.slice(i + 1);
  return ext != null && name.endsWith(ext) ? name.slice(0, -ext.length) : name;
}

function toPascalCase(id: string): string {
  const parts = id.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (parts.length === 0) return "Shader";
  return parts.map((p) => p[0]!.toUpperCase() + p.slice(1)).join("");
}

function uniformsInterfaceName(shaderId: string): string {
  return `${toPascalCase(shaderId)}ShaderUniforms`;
}

function aggregateInterfaceName(slabStem: string): string {
  return `${toPascalCase(slabStem)}SlabShaders`;
}

function jsdocLines(lines: string[], base: string): string {
  if (lines.length === 0) return "";
  if (lines.length === 1) return `${base}/** ${lines[0]} */\n`;
  return `${base}/**\n${lines.map((l) => `${base} * ${l}`).join("\n")}\n${base} */\n`;
}

function emitUniformField(u: UniformBindingMeta): string {
  const ind = "    ";
  const docs: string[] = [];

  if (u.mousePosition) {
    docs.push("mouse position in normalized canvas coordinates (read-only)");
    return `${jsdocLines(docs, ind)}${ind}readonly ${u.name}: readonly [number, number];\n`;
  }

  if ((u.slabType === "float" || u.slabType === "int") && u.range) {
    docs.push(`range: ${u.range[0]}-${u.range[1]}`);
  }
  if (u.hint === "color" && (u.slabType === "vec3" || u.slabType === "vec4")) {
    docs.push("color hint (same tuple shape as vec3/vec4)");
  }

  let ts: string;
  switch (u.slabType) {
    case "float":
    case "int":
      ts = "number";
      break;
    case "bool":
      ts = "boolean";
      break;
    case "vec2":
      ts = "[number, number]";
      break;
    case "vec3":
      ts = "[number, number, number]";
      break;
    case "vec4":
      ts = "[number, number, number, number]";
      break;
    case "sampler2D":
      ts = "HTMLImageElement | HTMLCanvasElement | ImageBitmap";
      break;
    default:
      ts = "unknown";
  }

  return `${jsdocLines(docs, ind)}${ind}${u.name}: ${ts};\n`;
}

function emitUniformsInterface(shaderId: string, uniforms: readonly UniformBindingMeta[]): string {
  const name = uniformsInterfaceName(shaderId);
  if (uniforms.length === 0) {
    return `  export interface ${name} {}\n`;
  }
  const fields = uniforms.map((u) => emitUniformField(u)).join("");
  return `  export interface ${name} {\n${fields}  }\n`;
}

function emitInnerBody(output: CompilerOutput, slabStem: string): string {
  const lines: string[] = [];
  for (const sh of output.shaders) {
    lines.push(emitUniformsInterface(sh.id, sh.metadata.uniforms));
  }

  const agg = aggregateInterfaceName(slabStem);
  lines.push(`  export interface ${agg} {\n`);
  for (const sh of output.shaders) {
    const iface = uniformsInterfaceName(sh.id);
    lines.push(`    readonly ${sh.exportName}: ShaderInstance<${iface}>;\n`);
  }
  lines.push("  }\n\n");

  for (const sh of output.shaders) {
    const iface = uniformsInterfaceName(sh.id);
    lines.push(`  export declare const ${sh.exportName}: ShaderInstance<${iface}>;\n`);
  }
  lines.push(`  export declare const __shaders: ${agg};\n`);
  return lines.join("");
}

/**
 * @param slabSourcePath Absolute or relative path to the `.slab` file (basename drives `declare module "./<file>.slab"`).
 */
export function emitSlabDts(output: CompilerOutput, slabSourcePath: string): string {
  const slabBase = fileBasename(slabSourcePath);
  const slabStem = fileBasename(slabSourcePath, ".slab");
  const inner = emitInnerBody(output, slabStem);
  return [
    "// Auto-generated by shaderlab — do not edit\n",
    `// Source: ${slabBase}\n\n`,
    `declare module "./${slabBase}" {\n`,
    '  import type { ShaderInstance } from "shaderlab";\n\n',
    inner,
    "}\n\nexport {};\n",
  ].join("");
}
